states:
#############################################
  #exogenous state variables, truncated_normal
  - name: thetax
    init:
      distribution: truncated_normal
      kwargs:
        mean: 0.512188
        stddev: 0.014856
        #stddev: 0.0397
  - name: epsilx
    init:
      distribution: truncated_normal
      kwargs:
        mean: 1.0
        stddev: 0.006753
  - name: muzstarx
    init:
      distribution: truncated_normal
      kwargs:
        mean: 1.00412
        stddev: 0.007058
  - name: muupx
    init:
      distribution: truncated_normal
      kwargs:
        mean: 1
        stddev:  0.006476
  - name: epspx
    init:
      distribution: truncated_normal
      kwargs:
        mean: 0.0
        stddev: 0.00026
  - name: pdx
    init:
      distribution: uniform
      kwargs:
        minval: 0.0071
        maxval: 0.0092
#############################################
  #endogenous state variables
  - name: pix
    init:
      distribution: uniform
      kwargs:
        minval: 1.005
        maxval: 1.007
        # ss : 1.00601
  - name: pstarx
    init:
      distribution: uniform
      kwargs:
        minval: 0.98
        maxval: 1.02
        # ss : 1
  - name: kstarx
    init:
      distribution: uniform
      kwargs:
        minval: 19.7
        maxval: 26.55
        # ss : 23.8651
  - name: cx
    init:
      distribution: uniform
      kwargs:
        minval: 1.37
        maxval: 1.675
        # ss :  1.57097
  - name: qx
    init:
      distribution: uniform
      kwargs:
        minval: 0.876
        maxval: 1.116
        # ss : 1
  - name: ix
    init:
      distribution: uniform
      kwargs:
        minval: 0.63
        maxval: 1.03
        # ss : 0.789654
  - name: nx
    init:
      distribution: uniform
      kwargs:
        minval: 8
        maxval: 16.4
        # ss :  12.6927
  - name: Rex
    init:
      distribution: uniform
      kwargs:
        minval: 0.0045
        maxval: 0.0215
        # ss :  0.0114707
  - name: wtildex
    init:
      distribution: uniform
      kwargs:
        minval: 1.69
        maxval: 1.85
        # ss : 1.7653
  - name: wstarx
    init:
      distribution: uniform
      kwargs:
        minval: 0.98
        maxval: 1.02
        # ss : 1
#############################################
policies:
  - name: piy
    bounds:
      # ss : 1.00601
      lower: 0.999
      upper: 1.001
      penalty_lower: 10.0
      penalty_upper: 10.0
    activation: implied
  - name: kstary
    bounds:
      # ss: 23.87
      lower: 0.825
      upper: 1.112
      penalty_lower: 10.0
      penalty_upper: 10.0
    activation: implied
  - name: cy
    bounds:
      # ss : 1.57 in level -> 0.414725
      lower: 0.52    # 1.37-0.7358438227*1.57
      upper: 1.25   # 1.675-0.7358438227*1.57
      penalty_lower: 10.0
      penalty_upper: 10.0
    activation: implied
  - name: pstary
    bounds:
      #ss : 1
      lower: 0.98
      upper: 1.02
      penalty_lower: 10.0
      penalty_upper: 10.0
    activation: implied
  - name: lambdazy
    bounds:
      # dynare 0.61
      lower: 0.88
      upper:  1.114
      penalty_lower: 10.0
      penalty_upper: 10.0
    activation: implied
  - name: qy
    bounds:
      lower: 0.876
      upper: 1.116
      penalty_lower: 10.0
      penalty_upper: 10.0
    activation: implied
  - name: omegabary
    bounds:
      #ss : 0.465
      lower: 0.7527
      upper: 1.1827
      penalty_lower: 10.0
      penalty_upper: 10.0
    activation: implied
  - name: iy
    bounds:
      #ss : 0.789654
      lower: 0.798   # 0.63/0.789654
      upper: 1.304  # 1.03/0.789654
      penalty_lower: 10.0
      penalty_upper: 10.0
    activation: implied
  - name: ny
    bounds:
      # ss : 12.69
      lower: 0.63
      upper: 1.29
      penalty_lower: 10.0
      penalty_upper: 10.0
    activation: implied
  - name: Rey
    bounds:
      #ss : 0.0114707
      lower: 0.4
      upper: 1.87
      penalty_lower: 10.0
      penalty_upper: 10.0
    activation: implied
  - name: wtildey
    bounds:
      # ss 1.7653
      lower: 0.957
      upper: 1.047
      penalty_lower: 10.0
      penalty_upper: 10.0
    activation: implied
  - name: sy
    bounds:
      # ss : 0.833333
      lower: 0.84
      upper: 1.08
      penalty_lower: 10.0
      penalty_upper: 10.0
    activation: implied
  - name: yzy
    bounds:
      # ss : 2.97298
      lower: 0.883
      upper: 1.077
      penalty_lower: 10.0
      penalty_upper: 10.0
    activation: implied
  - name: hy
    bounds:
      # ss : 1.01047
      lower: 0.89
      upper: 1.12
      penalty_lower: 10.0
      penalty_upper: 10.0
    activation: implied
  - name: rentky
    bounds:
      # ss : 0.0502465
      lower: 0.8
      upper: 1.2
      penalty_lower: 10.0
      penalty_upper: 10.0
    activation: implied
  - name: Rky
    bounds:
      #ss : 0.0189641
      lower: 0.1054
      upper: 4.95
      penalty_lower: 10.0
      penalty_upper: 10.0
    activation: implied
  - name: Fpy
    bounds:
      # ss : 6.978
      lower: 0.888
      upper: 1.096
      penalty_lower: 10.0
      penalty_upper: 10.0
    activation: implied
  - name: Kpy
    bounds:
      # ss : 6.98355
      lower: 0.88
      upper: 1.109
      penalty_lower: 10.0
      penalty_upper: 10.0
    activation: implied
  - name: Fwy
    bounds:
      # ss : 2.335
      lower: 0.7066381156
      upper: 1.285
      penalty_lower: 10.0
      penalty_upper: 10.0
    activation: implied
  - name: Kwy
    bounds:
      #ss : 5.42373
      lower: 0.4277
      upper: 1.5229
      penalty_lower: 10.0
      penalty_upper: 10.0
    activation: implied
  - name: wtary
    bounds:
      #ss : 1
      lower: 1.02
      upper: 0.98
      penalty_lower: 10.0
      penalty_upper: 10.0
    activation: implied
  - name: uy
    bounds:
      #ss : 1
      lower: 1.02
      upper: 0.96
      penalty_lower: 1000.0
      penalty_upper: 1000.0
    activation: implied
#############################################
definitions:
  - name: pitilde
  - name: pitildew
  - name: piw
  - name: autil
  - name: s_invest
  - name: spr_invest
  - name: Fomegabar
  - name: Gomegabar
  - name: kbarx
  - name: p_d
  - name: piy_norm
  - name: kstary_norm
  - name: cy_norm
  - name: lambdazy_norm
  - name: omegabary_norm
  - name: ny_norm
  - name: Rey_norm
  - name: wtildey_norm
  - name: sy_norm
  - name: yzy_norm
  - name: hy_norm
  - name: rentky_norm
  - name: Rky_norm
  - name: Fpy_norm
  - name: Kpy_norm
  - name: Fwy_norm
  - name: Kwy_norm
