states:
  #exogenous state variables, uniformly samples
  #- name: Ax
    #init:
      #distribution: uniform
      #kwargs:
        #minval: 0.888
        #maxval: 1.127   
  #- name: Gx
    #init:
      #distribution: uniform
      #kwargs:
        #minval: 0.127
        #maxval: 0.177   
  #- name: Zx
    #init:
      #distribution: uniform
      #kwargs:
        #minval: 0.706
        #maxval: 1.416   
  #- name: nux
    #init:
      #distribution: uniform
      #kwargs:
        #minval: 0.787
        #maxval: 1.270   
  #- name: psix
    #init:
      #distribution: uniform
      #kwargs:
        #minval: 2.14
        #maxval: 16.82   
  #- name: mx 
    #init:
      #distribution: uniform
      #kwargs:
        #minval: -0.0078
        #maxval: 0.0078   
#############################################                
  #exogenous state variables, truncated_normal
  - name: Ax
    init:
      distribution: truncated_normal
      kwargs:
        mean: 1.0
        stddev: 0.0397 
  - name: Gx
    init:
      distribution: truncated_normal
      kwargs:
        mean: 0.1500
        stddev: 0.0548   
  - name: Zx
    init:
      distribution: truncated_normal
      kwargs:
        mean: 1.0
        stddev: 0.1160   
  - name: nux
    init:
      distribution: truncated_normal
      kwargs:
        mean: 1.0
        stddev: 0.0797   
  - name: psix
    init:
      distribution: truncated_normal
      kwargs:
        mean: 6.0
        stddev: 0.3436 
  - name: mx 
    init:
      distribution: truncated_normal
      kwargs:
        mean: 0.0
        stddev: 0.0026         
#############################################        
  #endogenous state variables
  - name: Kx
    init:
      distribution: uniform
      kwargs:
        minval: 6.7
        maxval: 8.2 
  - name: Cx
    init:
      distribution: uniform
      kwargs:
        minval: 0.37
        maxval: 0.45  
  - name: Ix
    init:
      distribution: uniform
      kwargs:
        minval: 0.13
        maxval: 0.24    
  - name: Yx
    init:
      distribution: uniform
      kwargs:
        minval: 0.67
        maxval: 0.82   
  - name: wx
    init:
      distribution: uniform
      kwargs:
        minval: 1.07
        maxval: 1.31    
  - name: nupx
    init:
      distribution: uniform
      kwargs:
        minval: 1.0
        maxval: 1.002   
  - name: pix
    init:
      distribution: uniform
      kwargs:
        minval: -0.01
        maxval: 0.02 
  - name: ix
    init:
      distribution: uniform
      kwargs:
        minval: -0.005
        maxval: 0.025    
#############################################                
policies:
  - name: lambday
    bounds: 
      #lower: 0.78
      #upper: 4.46
      lower: 1.5616
      upper: 3.6436     
      penalty_lower: 10.0
      penalty_upper: 10.0
    #activation: tf.nn.softplus      
    #activation: implied                     
  - name: muy
    bounds: 
      #lower: 0.78
      #upper: 4.46
      lower: 1.5616
      upper: 3.6436     
      penalty_lower: 10.0
      penalty_upper: 10.0  
    #activation: tf.nn.softplus      
    #activation: implied                     
#rescaled equation      
  - name: Cy
    bounds: 
      lower: 0.0099
      #upper: 0.05
      upper: 0.0398
      penalty_lower: 1000.0
      penalty_upper: 1000.0 
    #activation: tf.nn.softplus
    activation: implied                
  - name: iy
    bounds:
      #lower: -0.09
      #upper:  0.11
      lower: -0.0399
      upper:  0.0601      
      penalty_lower: 100.0
      penalty_upper: 100.0    
    #activation: implied                     
  - name: piy
    bounds: 
      #lower: -0.1
      #upper: 0.11
      lower: -0.0450
      upper: 0.0550     
      penalty_lower: 100.0
      penalty_upper: 100.0    
    #activation: implied                     
  - name: pihashy
    bounds: 
      #lower: -0.085
      #upper:  0.12
      lower:  -0.0324
      upper:  0.0676     
      penalty_lower: 1000.0
      penalty_upper: 1000.0  
    #activation: implied                           
  - name: Ry
    bounds: 
      lower: -0.0200
      upper: 0.0800  
      penalty_lower: 100.0
      penalty_upper: 100.0 
    #activation: implied                                 
  - name: uy
    bounds: 
      lower: 0.8000
      upper: 1.2
      penalty_lower: 10.0
      penalty_upper: 10.0 
    activation: implied
    #activation: tf.nn.softplus    
#rescaled equation
  #- name: Iy
    #bounds: 
      #lower: 0.4
      #upper: 1.6
      #penalty_lower: 10.0
      #penalty_upper: 10.0 
    #activation: tf.nn.softplus      
    ###activation: implied                                       
#non-rescaled equation
  - name: Iy
    bounds: 
      #lower: 0.6
      #upper: 1.4
      lower: 0.06
      upper: 0.31      
      penalty_lower: 100.0
      penalty_upper: 100.0       
    #activation: tf.nn.softplus      
    activation: implied          
  - name: wy
    bounds: 
      #lower: 0.8
      #upper: 1.6
      lower: 0.9530
      upper: 1.4296  
      penalty_lower: 100.0
      penalty_upper: 100.0 
    #activation: tf.nn.softplus      
    #activation: implied                                             
  - name: whashy
    bounds: 
      #lower: 0.8
      #upper: 1.6
      lower: 0.9575
      upper: 1.4362     
      penalty_lower: 100.0
      penalty_upper: 100.0 
    #activation: tf.nn.softplus      
    #activation: implied                                                   
  - name: h1y
    bounds: 
      lower: 1.2254
      upper: 2.2467
      #lower: 1e-6 
      #upper: 2.95      
      penalty_lower: 10.0
      penalty_upper: 10.0 
    #activation: tf.nn.softplus      
    #activation: implied                                                         
  - name: h2y
    bounds: 
      lower: 2.0478
      upper: 3.7542
      #lower: 1e-6
      #upper: 5.00      
      penalty_lower: 10.0
      penalty_upper: 10.0 
    #activation: tf.nn.softplus      
    #activation: implied                                                               
  - name: Ny
    bounds: 
      lower: 0.3540
      upper: 0.5310
      penalty_lower: 100.0
      penalty_upper: 100.0   
    #activation: implied  
    #activation: tf.nn.softplus    
  - name: Khaty
    bounds: 
      #lower: 5.3
      #upper: 9.7  
      lower: 6.0193
      upper: 9.0289        
      penalty_lower: 10.0
      penalty_upper: 10.0 
    #activation: tf.nn.softplus      
    #activation: implied                                                                           
  - name: Ky
    bounds: 
      #lower: 5.3
      #upper: 9.7  
      lower: 6.0193
      upper: 9.0289         
      penalty_lower: 10.0
      penalty_upper: 10.0 
    #activation: tf.nn.softplus      
    #activation: implied                                                                                 
  - name: mcy
    bounds: 
      lower: 0.5819
      upper: 0.8728
      penalty_lower: 100.0
      penalty_upper: 100.0 
    #activation: tf.nn.softplus      
    #activation: implied                                                                                       
  - name: x1y
    bounds: 
      lower: 4.2776
      upper: 6.4164
      #lower: 1e-6
      #upper: 8.55        
      penalty_lower: 10.0
      penalty_upper: 10.0 
    #activation: tf.nn.softplus      
    #activation: implied                                                                                             
  - name: x2y
    bounds: 
      lower: 5.2807
      upper: 7.9210
      #lower: 1e-6
      #upper: 8.55         
      penalty_lower: 10.0
      penalty_upper: 10.0
    #activation: tf.nn.softplus      
    #activation: implied                                                                                                   
  - name: Yy
    bounds: 
      lower: 0.6024
      upper: 0.9036  
      penalty_lower: 10.0
      penalty_upper: 10.0    
    #activation: tf.nn.softplus      
    #activation: implied                                                                                                         
  - name: nupy
    bounds: 
      #lower: 0.9972
      #upper: 1.0110 
      lower: 1.0
      upper: 1.002       
      penalty_lower: 1000.0
      penalty_upper: 1000.0  
    activation: implied    
#############################################            
definitions:
  - name: delta_1
