states:
  #exogenous state variables
  - name: Ax
  - name: Gx
  - name: Zx
  - name: nux
  - name: psix
  - name: mx 
  #endogenous state variables
  - name: Kx
    init:
      distribution: uniform
      kwargs:
        minval: 6.7
        maxval: 8.2 
  - name: Cx
    init:
      distribution: uniform
      kwargs:
        minval: 0.37
        maxval: 0.45  
  - name: Ix
    init:
      distribution: uniform
      kwargs:
        minval: 0.13
        maxval: 0.24    
  - name: Yx
    init:
      distribution: uniform
      kwargs:
        minval: 0.67
        maxval: 0.82   
  - name: wx
    init:
      distribution: uniform
      kwargs:
        minval: 1.07
        maxval: 1.31    
  - name: nupx
    init:
      distribution: uniform
      kwargs:
        minval: 1.0
        maxval: 1.002   
  - name: pix
    init:
      distribution: uniform
      kwargs:
        minval: -0.01
        maxval: 0.02 
  - name: ix
    init:
      distribution: uniform
      kwargs:
        minval: -0.005
        maxval: 0.025     
policies:
  - name: lambday
    bounds: 
      lower: 0.1
      upper: 7.0
      penalty_lower: 10.0
      penalty_upper: 10.0
  - name: muy
    bounds: 
      lower: 1.3
      upper: 4.0
      penalty_lower: 10.0
      penalty_upper: 10.0      
#rescaled equation      
  - name: Cy
    bounds: 
      lower: 0.001
      upper: 0.12
      penalty_lower: 10.0
      penalty_upper: 10.0 
    activation: implied               
#non-rescaled equation      
  #- name: Cy
    #bounds: 
      #lower: 0.29
      #upper: 0.54      
  - name: iy
    bounds: 
      lower: -0.06
      upper: 0.1
      penalty_lower: 10.0
      penalty_upper: 10.0      
  - name: piy
    bounds: 
      lower: -0.05
      upper: 0.06
      penalty_lower: 10.0
      penalty_upper: 10.0      
  - name: pihashy
    bounds: 
      lower: -0.15
      upper: 0.15
      penalty_lower: 10.0
      penalty_upper: 10.0      
  - name: Ry
    bounds: 
      lower: -0.02
      upper: 0.06   
      penalty_lower: 10.0
      penalty_upper: 10.0      
  - name: uy
    bounds: 
      lower: 0.1
      upper: 1.6
      penalty_lower: 10.0
      penalty_upper: 10.0      
#rescaled equation
  - name: Iy
    bounds: 
      lower: 0.01
      upper: 10.0
      penalty_lower: 10.0
      penalty_upper: 10.0      
#non-rescaled equation
  #- name: Iy
    #bounds: 
      #lower: 0.01
      #upper: 10.0      
  - name: wy
    bounds: 
      lower: 0.2
      upper: 1.9
      penalty_lower: 10.0
      penalty_upper: 10.0      
  - name: whashy
    bounds: 
      lower: 0.2
      upper: 2.1
      penalty_lower: 10.0
      penalty_upper: 10.0      
  - name: h1y
    bounds: 
      lower: 0.5
      upper: 3.0
      penalty_lower: 10.0
      penalty_upper: 10.0      
  - name: h2y
    bounds: 
      lower: 0.7
      upper: 4.0
      penalty_lower: 10.0
      penalty_upper: 10.0      
  - name: Ny
    bounds: 
      lower: 0.2
      upper: 0.8 
      penalty_lower: 10.0
      penalty_upper: 10.0      
  - name: Khaty
    bounds: 
      lower: 1.0
      upper: 12.0  
      penalty_lower: 10.0
      penalty_upper: 10.0      
  - name: Ky
    bounds: 
      lower: 4.0
      upper: 10.0    
      penalty_lower: 10.0
      penalty_upper: 10.0      
  - name: mcy
    bounds: 
      lower: 0.3
      upper: 1.2    
      penalty_lower: 10.0
      penalty_upper: 10.0      
  - name: x1y
    bounds: 
      lower: 2.0
      upper: 10.0  
      penalty_lower: 10.0
      penalty_upper: 10.0      
  - name: x2y
    bounds: 
      lower: 3.0
      upper: 10.0  
      penalty_lower: 10.0
      penalty_upper: 10.0
  - name: Yy
    bounds: 
      lower: 0.4
      upper: 1.1  
      penalty_lower: 10.0
      penalty_upper: 10.0      
  - name: nupy
    bounds: 
      lower: 0.95
      upper: 1.1  
      penalty_lower: 10.0
      penalty_upper: 10.0      
definitions:
  - name: delta_1
