states:
  #exogenous state variables
  - name: Ax
    bounds: 
      lower: 0.8877
      upper: 1.1265   
  - name: Gx
    bounds: 
      lower: 0.1273
      upper: 0.1768   
  - name: Zx
    bounds: 
      lower: 0.7061
      upper: 1.4162   
  - name: nux
    bounds: 
      lower: 0.7873
      upper: 1.2702   
  - name: psix
    bounds: 
      lower: 2.1405
      upper: 16.8184   
  - name: mx
    bounds: 
      lower: -0.01
      upper: 0.01   
  #endogenous state variables
  - name: Kx
    bounds: 
      lower: 6.7251
      upper: 8.2196  
  - name: Cx
    bounds: 
      lower: 0.3703
      upper: 0.4526   
  - name: Ix
    bounds: 
      lower: 0.1308
      upper: 0.2429     
  - name: Yx
    bounds: 
      lower: 0.6731
      upper: 0.8226    
  - name: wx
    bounds: 
      lower: 1.0722
      upper: 1.3104    
  - name: nupx
    bounds: 
      lower: 1.0001
      upper: 1.0022    
  - name: pix
    bounds: 
      lower: -0.0100
      upper: 0.0200  
  - name: ix
    bounds: 
      lower: -0.0049
      upper: 0.0251        
policies:
  - name: lambday
    bounds: 
      lower: 2.0965
      upper: 3.1447
    activation: "lambda x: tf.math.sigmoid(x) * (3.1447 - 2.0965) + 2.0965"
  - name: muy
    bounds: 
      lower: 2.0965
      upper: 3.1447
    activation: "lambda x: tf.math.sigmoid(x) * (3.1447 - 2.0965) + 2.0965"
  - name: Cy
    bounds: 
      lower: 0.3292
      upper: 0.4938
    activation: "lambda x: tf.math.sigmoid(x) * (0.4938 - 0.3292) + 0.3292"
  - name: iy
    bounds: 
      lower: -0.0199
      upper: 0.0401 
    activation: "lambda x: tf.math.sigmoid(x) * (0.0401 + 0.0199) - 0.0199"
  - name: piy
    bounds: 
      lower: -0.0250
      upper: 0.0350 
    activation: "lambda x: tf.math.sigmoid(x) * (0.0350 + 0.0250) - 0.0250"
  - name: pihashy
    bounds: 
      lower: 0.0476
      upper: 1.9909
    activation: "lambda x: tf.math.sigmoid(x) * (1.9909 - 0.0476) + 0.0476"
  - name: Ry
    bounds: 
      lower: 0.0000
      upper: 0.0600   
      penalty_lower: 100000000.0
    activation: "lambda x: tf.math.sigmoid(x) * (0.0600 - 0.0000) + 0.0000"
  - name: uy
    bounds: 
      lower: 0.7000
      upper: 1.3000     
    activation: "lambda x: tf.math.sigmoid(x) * (1.3000 - 0.7000) + 0.7000"
  - name: Iy
    bounds: 
      lower: 0.1046
      upper: 0.2914
    activation: "lambda x: tf.math.sigmoid(x) * (0.2914 - 0.1046) + 0.1046"
  - name: wy
    bounds: 
      lower: 0.8339
      upper: 1.5487
    activation: "lambda x: tf.math.sigmoid(x) * (1.5487 - 0.8339) + 0.8339"
  - name: whashy
    bounds: 
      lower: 0.8378
      upper: 1.5559
    activation: "lambda x: tf.math.sigmoid(x) * (1.5559 - 0.8378) + 0.8378"
  - name: h1y
    bounds: 
      lower: 1.1697
      upper: 2.1724  
    activation: "lambda x: tf.math.sigmoid(x) * (2.1724 - 1.1697) + 1.1697"
  - name: h2y
    bounds: 
      lower: 1.9909
      upper: 3.6973   
    activation: "lambda x: tf.math.sigmoid(x) * (3.6973 - 1.9909) + 1.9909"
  - name: Ny
    bounds: 
      lower: 0.3076
      upper: 0.5713 
    activation: "lambda x: tf.math.sigmoid(x) * (0.5713 - 0.3076) + 0.3076"
  - name: Khaty
    bounds: 
      lower: 5.2306
      upper: 9.7141  
    activation: "lambda x: tf.math.sigmoid(x) * (9.7141 - 5.2306) + 5.2306"
  - name: Ky
    bounds: 
      lower: 5.2306
      upper: 9.7141    
    activation: "lambda x: tf.math.sigmoid(x) * (9.7141 - 5.2306) + 5.2306"
  - name: mcy
    bounds: 
      lower: 0.5092
      upper: 0.9456    
    activation: "lambda x: tf.math.sigmoid(x) * (0.9456 - 0.5092) + 0.5092"
  - name: x1y
    bounds: 
      lower: 3.7429
      upper: 6.9511  
    activation: "lambda x: tf.math.sigmoid(x) * (6.9511 - 3.7429) + 3.7429"
  - name: x2y
    bounds: 
      lower: 4.6206
      upper: 8.5811   
    activation: "lambda x: tf.math.sigmoid(x) * (8.5811 - 4.6206) + 4.6206"
  - name: Yy
    bounds: 
      lower: 0.5235
      upper: 0.9722   
    activation: "lambda x: tf.math.sigmoid(x) * (0.9722 - 0.5235) + 0.5235"
  - name: nupy
    bounds: 
      lower: 0.9972
      upper: 1.0110   
    activation: "lambda x: tf.math.sigmoid(x) * (1.0110 - 0.9972) + 0.9972"
definitions:
  - name: delta_1
