states:
  #exogenous state variables
  - name: Ax
  - name: Gx
  - name: Zx
  - name: nux
  - name: psix
  - name: mx 
  #endogenous state variables
  - name: Kx
    bounds: 
      lower: 1.0
      upper: 20.0  
  #- name: Cx
    #bounds: 
      #lower: 0.1
      #upper: 1.0  
  - name: Cx      
    init:
      distribution: uniform
      kwargs:
        minval: 0.37
        maxval: 0.45        
  - name: Ix
    bounds: 
      lower: 0.001
      upper: 0.5     
  - name: Yx
    bounds: 
      lower: 0.1
      upper: 10.0    
  - name: wx
    bounds: 
      lower: 0.1
      upper: 2.0    
  - name: nupx
    bounds: 
      lower: 0.5
      upper: 1.5    
  #- name: pix
    #bounds: 
      #lower: -0.05
      #upper: 0.05  
  - name: pix
    init:
      distribution: uniform
      kwargs:
        minval: -0.01
        maxval: 0.02       
  - name: ix
    bounds: 
      lower: -0.05
      upper: 0.05        
policies:
  - name: lambday
    bounds: 
      lower: 1e-6
  - name: muy
    bounds: 
      lower: 1e-6
  #- name: Cy
    #activation: tf.nn.softplus
  - name: Cy
    bounds: 
      lower: 0.28
      upper: 0.55    
  - name: iy
    bounds: 
      lower: -10.0
      upper: 10.0 
  - name: piy
    bounds: 
      lower: -0.025
      upper: 0.035
  - name: pihashy
    bounds: 
      lower: -0.015
      upper: 0.045            
  #- name: piy
    #bounds: 
      #lower: -2.0
      #upper: 100.0 
  #- name: pihashy
    #bounds: 
      #lower: -2.0
      #upper: 100.0
  - name: Ry
    bounds: 
      lower: 0.0
      penalty_lower: 10000.0
  - name: uy
    bounds: 
      lower: 0.001
  - name: Iy
    bounds: 
      lower: 0.05
      upper: 0.5
  - name: wy
    bounds: 
      lower: 0.1
      upper: 3.0
  - name: whashy
    bounds: 
      lower: 0.1
      upper: 3.0
  - name: h1y
    bounds: 
      lower: 0.01
  - name: h2y
    bounds: 
      lower: 0.5
  - name: Ny
    bounds: 
      lower: 0.1
      upper: 1.0 
  - name: Khaty
    bounds: 
      lower: 1.0
      upper: 10.0  
  - name: Ky
    bounds: 
      lower: 0.10
      upper: 20.0    
  - name: mcy
    bounds: 
      lower: 0.1
      upper: 2.0    
  - name: x1y
    bounds: 
      lower: 0.0001
  - name: x2y
    bounds: 
      lower: 0.0001
  - name: Yy
    bounds: 
      lower: 0.01
      upper: 10.0   
  - name: nupy
    bounds: 
      lower: 0.9
      upper: 1.1   
definitions:
  - name: delta_1
