states:
  #exogenous state variables, uniformly samples
  #- name: Ax
    #init:
      #distribution: uniform
      #kwargs:
        #minval: 0.888
        #maxval: 1.127   
  #- name: Gx
    #init:
      #distribution: uniform
      #kwargs:
        #minval: 0.127
        #maxval: 0.177   
  #- name: Zx
    #init:
      #distribution: uniform
      #kwargs:
        #minval: 0.706
        #maxval: 1.416   
  #- name: nux
    #init:
      #distribution: uniform
      #kwargs:
        #minval: 0.787
        #maxval: 1.270   
  #- name: psix
    #init:
      #distribution: uniform
      #kwargs:
        #minval: 2.14
        #maxval: 16.82   
  #- name: mx 
    #init:
      #distribution: uniform
      #kwargs:
        #minval: -0.0078
        #maxval: 0.0078   
#############################################                
  #exogenous state variables, truncated_normal
  - name: Ax
    init:
      distribution: truncated_normal
      kwargs:
        mean: 1.0
        stddev: 0.000397 
        #stddev: 0.00397 
        #stddev: 0.0397 
  - name: Gx
    init:
      distribution: truncated_normal
      kwargs:
        mean: 0.1500
        #stddev: 0.0548   
        #stddev: 0.00548
        stddev: 0.000548           
  - name: Zx
    init:
      distribution: truncated_normal
      kwargs:
        mean: 1.0
        #stddev: 0.1160   
        #stddev: 0.01160
        stddev: 0.001160                   
  - name: nux
    init:
      distribution: truncated_normal
      kwargs:
        mean: 1.0
#        stddev: 0.0797   
        #stddev: 0.00797
        stddev: 0.000797           
  - name: psix
    init:
      distribution: truncated_normal
      kwargs:
        mean: 6.0
#        stddev: 0.0572 
        #stddev: 0.00572 
        stddev: 0.000572         
  - name: mx 
    init:
      distribution: truncated_normal
      kwargs:
        mean: 0.0
#        stddev: 0.0026         
        #stddev: 0.00026         
        stddev: 0.000026         
#############################################        
  #endogenous state variables
  - name: Kx
    init:
      distribution: uniform
      kwargs:
        #minval: 6.7
        #maxval: 8.2 
        minval: 7.3979
        maxval: 7.5471         
  - name: Cx
    init:
      distribution: uniform
      kwargs:
        #minval: 0.37
        #maxval: 0.45  
        minval: 0.4074
        maxval: 0.4156          
  - name: Ix
    init:
      distribution: uniform
      kwargs:
        #minval: 0.13
        #maxval: 0.24 
        minval: 0.1812
        maxval: 0.1924           
  - name: Yx
    init:
      distribution: uniform
      kwargs:
        #minval: 0.67
        #maxval: 0.82   
        minval: 0.7404
        maxval: 0.7703         
  - name: wx
    init:
      distribution: uniform
      kwargs:
        #minval: 1.07
        #maxval: 1.31    
        minval: 1.1556
        maxval: 1.2270           
  - name: nupx
    init:
      distribution: uniform
      kwargs:
        #minval: 1.0
        #maxval: 1.0082           
        minval: 1.0005
        maxval: 1.0007           
  - name: pix
    init:
      distribution: uniform
      kwargs:
        #minval: -0.01
        #maxval: 0.02 
        minval: 0.0035
        maxval: 0.0065         
  - name: ix
    init:
      distribution: uniform
      kwargs:
        #minval: -0.005
        #maxval: 0.025
        minval: 0.0086
        maxval: 0.0116          
#############################################                
policies:
  - name: lambday
    activation: tf.nn.softplus      
  - name: muy
    activation: tf.nn.softplus      
#rescaled equation      
  - name: Cy
    activation: tf.nn.softplus
  #- name: iy
    #bounds:
      ##lower: -0.09z
      ##upper:  0.11
      #lower: -0.0399
      #upper:  0.0601      
      #penalty_lower: 100.0
      #penalty_upper: 100.0    
    #activation: implied                     
  - name: piy  
    activation: tf.nn.softplus                   
  - name: pihashy
    activation: tf.nn.softplus                          
  - name: Ry
    activation: tf.nn.softplus                                                                
#non-rescaled equation
  - name: Iy
    activation: tf.nn.softplus      
  - name: wy
    activation: tf.nn.softplus      
  - name: whashy    
    activation: tf.nn.softplus                                                   
  - name: h1y
    activation: tf.nn.softplus                                                            
  - name: h2y
    activation: tf.nn.softplus                                                                    
  - name: Ny
    activation: tf.nn.softplus    
  #- name: Khaty
    #bounds: 
      ##lower: 5.3
      ##upper: 9.7  
      ##lower: 6.0193
      ##upper: 9.0289 
      #lower: 4.0193
      #upper: 11.0289      
      #penalty_lower: 10.0
      #penalty_upper: 10.0 
    ##activation: tf.nn.softplus      
    #activation: implied                                                                           
  #- name: Ky
    #bounds: 
      ##lower: 5.3
      ##upper: 9.7  
      ##lower: 6.0193
      ##upper: 9.0289         
      #lower: 5.0193
      #upper: 10.0289     
      #penalty_lower: 10.0
      #penalty_upper: 10.0 
    ##activation: tf.nn.softplus      
    #activation: implied                                                                                 
  - name: mcy
    activation: tf.nn.softplus                                                                                      
  - name: x1y
    activation: tf.nn.softplus                                                                                           
  - name: x2y
    activation: tf.nn.softplus                                                                                               
  - name: Yy
    activation: tf.nn.softplus                                                                                                       
  - name: nupy
    #bounds: 
      #lower: 0.95
      #upper: 1.05        
      #penalty_lower: 1000.0
      #penalty_upper: 1000.0  
    #activation: implied 
    activation: tf.nn.softplus 
#############################################            
definitions:
  - name: delta_1
  - name: Ky
  - name: iy
  - name: lambday_norm 
  - name: Cy_norm
  - name: piy_norm
  - name: pihashy_norm
  - name: muy_norm
  - name: Iy_norm
  - name: Ry_norm
  - name: h1y_norm
  - name: h2y_norm
  - name: whashy_norm
  - name: wy_norm
  - name: Ny_norm
  - name: mcy_norm
  - name: x1y_norm
  - name: x2y_norm
  - name: Yy_norm
  - name: nupy_norm
