states:
  - name: rf
  - name: yT
  - name: delta
  - name: b_old
  - name: pN_old
  - name: disp_old
  - name: kappa_ewma
    init:
      distribution: uniform
      kwargs:
        minval: 1.38
        maxval: 1.54  
  - name: debt_to_gdp_ewma
  - name: budget_viol_ewma
    init:
      distribution: uniform
      kwargs:
        minval: 0.04
        maxval: 0.05 
policies:
  - name: nu
    bounds:
      upper: 10000.0
  - name: q_real
    bounds:
      lower: 0.1
      upper: 1.4
  - name: m_imp
    bounds:
      lower: 0.02
      upper: 0.395
  - name: cT
    bounds:
      lower: 0.01
      upper: 1.0
  - name: h_work
    bounds:
      lower: 0.03
      upper: 1.7
  - name: Lambda
    bounds:
      lower: 0.5
      upper: 50.0
  - name: c_tot
    bounds:
      lower: 0.35
      upper: 2.8
  - name: cN
    bounds:
      lower: 0.01
      upper: 2.5
  - name: num
    bounds:  
      lower: 5.0
      upper: 320.0
  - name: den
    bounds: 
      lower: 10.0
      upper: 320.0
  - name: pN
    bounds:
      lower: 0.35
      upper: 2.08
  - name: piN
    bounds:
      lower: -0.1
      upper: 0.1
  - name: pi_tot
    bounds:
      lower: -0.04
      upper: 0.2
  - name: p_x
    bounds:
      lower: 0.1
      upper: 1.6
    activation: tf.nn.relu
  - name: i_nom
    bounds:
      lower: -0.06
      upper: 0.6
  - name: r_real
    bounds:
      lower: -0.05
      upper: 0.40
  - name: disp
    bounds:
      lower: 0.1
      upper: 5.1
  - name: mu
  - name: kappa
    bounds:
      lower: 0.01
      upper: 4.0
definitions:
  - name: pT
  - name: tradeb
  - name: yN
  - name: wage
  - name: bigQ_real
  - name: pNtilde
  - name: phi
  - name: y_tot
  - name: b_new
    bounds:
      lower: 0.001
      upper: 5.0
  - name: debt_to_gdp
  - name: budget_viol
      
      