states:
  - name: rf
  - name: yT
  - name: delta
  - name: b_old
  - name: pN_old
  - name: disp_old
  - name: kappa_ewma
    init:
      distribution: uniform
      kwargs:
        minval: 1.38
        maxval: 1.54  
  - name: beta_ewma
    init:
      distribution: uniform
      kwargs:
        minval: 0.8
        maxval: 0.995           
  - name: debt_to_gdp_ewma
  - name: budget_viol_ewma
    init:
      distribution: uniform
      kwargs:
        minval: 0.00
        maxval: 0.08 
policies:
  - name: nu
    bounds:
      lower: 0
      upper: 5.0
      penalty_lower: 100000000.0
    activation: "lambda x: tf.math.sigmoid(x) * (5.0 - 0.0) + 0.0"
  - name: q_real
    bounds:
      lower: 0.1
      upper: 1.4
    activation: "lambda x: tf.math.sigmoid(x) * (1.4 - 0.1) + 0.1"
  - name: m_imp
    bounds:
      lower: 0.02
      upper: 0.395
    activation: "lambda x: tf.math.sigmoid(x) * (0.395 - 0.02) + 0.02"
  - name: cT
    bounds:
      lower: 0.01
      upper: 1.0
    activation: "lambda x: tf.math.sigmoid(x) * (1.0 - 0.01) + 0.01"
  - name: h_work
    bounds:
      lower: 0.03
      upper: 1.7
    activation: "lambda x: tf.math.sigmoid(x) * (1.7 - 0.03) + 0.03"
  - name: Lambda
    bounds:
      lower: 0.5
      upper: 50.0
    activation: "lambda x: tf.math.sigmoid(x) * (50.0 - 0.5) + 0.5"
  - name: c_tot
    bounds:
      lower: 0.35
      upper: 2.8
    activation: "lambda x: tf.math.sigmoid(x) * (2.8 - 0.35) + 0.35"
  - name: cN
    bounds:
      lower: 0.01
      upper: 2.5
    activation: "lambda x: tf.math.sigmoid(x) * (2.5 - 0.01) + 0.01"
  - name: num
    bounds:  
      lower: 5.0
      upper: 320.0
    activation: "lambda x: tf.math.sigmoid(x) * (320.0 - 5.0) + 5.0"
  - name: den
    bounds: 
      lower: 10.0
      upper: 320.0
    activation: "lambda x: tf.math.sigmoid(x) * (320.0 - 10.0) + 10.0"
  - name: pN
    bounds:
      lower: 0.35
      upper: 2.08
    activation: "lambda x: tf.math.sigmoid(x) * (2.08 - 0.35) + 0.35"
  - name: piN
    bounds:
      lower: -0.1
      upper: 0.1
    activation: "lambda x: tf.math.sigmoid(x) * (0.1 + 0.1) - 0.1"
  - name: pi_tot
    bounds:
      lower: -0.04
      upper: 0.2
    activation: "lambda x: tf.math.sigmoid(x) * (0.2 + 0.04) - 0.04"
  - name: p_x
    bounds:
      lower: 0.1
      upper: 1.6
    activation: "lambda x: tf.math.sigmoid(x) * (1.6 - 0.1) + 0.1"
  - name: i_nom
    bounds:
      lower: -0.06
      upper: 0.6
    activation: "lambda x: tf.math.sigmoid(x) * (0.6 + 0.06) - 0.06"
  - name: r_real
    bounds:
      lower: -0.05
      upper: 0.40
    activation: "lambda x: tf.math.sigmoid(x) * (0.40 + 0.05) - 0.05"
  - name: disp
    bounds:
      lower: 0.1
      upper: 5.1
    activation: "lambda x: tf.math.sigmoid(x) * (5.1 - 0.1) + 0.1"
  - name: mu
    bounds: 
      lower: 0
      upper: 100.0
      penalty_lower: 100000000.0
    activation: "lambda x: tf.math.sigmoid(x) * (100.0 - 0.0) + 0.0"
  - name: kappa
    bounds:
      lower: 1.35
      upper: 1.6
    activation: "lambda x: tf.math.sigmoid(x) * (1.6 - 1.35) + 1.35"
  - name: beta
    bounds:
      lower: 0.7
      upper: 0.99
    activation: "lambda x: tf.math.sigmoid(x) * (0.99 - 0.7) + 0.7"
definitions:
  - name: pT
  - name: tradeb
  - name: yN
  - name: wage
  - name: bigQ_real
  - name: pNtilde
  - name: phi
  - name: y_tot
  - name: b_new
    bounds:
      lower: 0.001
      upper: 5.0
  - name: debt_to_gdp
  - name: budget_viol
      
      