constants:
    alpha: 0.3
    beta: 0.995
    b_habit: 0.94
    eps_p: 5.0
    eps_w: 2.0
    phi_w: 0.6
    phi_p: 0.72  
    pi_ss: 0.005
    i_ss: 0.01
    i_LB: -0.10
    zeta_w: 0.38
    zeta_p: 0.06
    chi: 1.66
    #kappa: 4.05
    kappa: 0.0
    delta_0: 0.025
    rho_i: 0.87
    phi_pi: 2.23
    phi_y: 1.06
    psi: 6.0
    rho_A: 0.99
    rho_Z: 0.83
    rho_G: 0.98
    rho_nu: 0.31
    rho_psi: 0.96
    #s_A: 0.0056
    #s_A: 0.00056
    s_A: 0.000056    
    #s_Z: 0.0647
    #s_Z: 0.00647
    s_Z: 0.000647    
    #s_G: 0.0109
    #s_G: 0.00109    
    s_G: 0.000109    
    #s_nu: 0.0758
    #s_nu: 0.00758
    s_nu: 0.000758        
    #s_psi: 0.0962
    #s_psi: 0.01603
    #s_psi: 0.001603     
    s_psi: 0.0001603         
    #s_i: 0.0026
    #s_i: 0.00026
    s_i: 0.000026    
    s_w: 0.0061
    omega: 0.2
    G_gov: 0.1496
    F_prod: 0.2799
    division_eps: 0.001
    # steady states 
    lambday_ss: 2.62
    muy_ss: 2.62
    Cy_ss: 0.0247 
    iy_ss: 0.0101
    piy_ss: 0.005
    pihashy_ss: 0.0176 
    Ry_ss: 0.03
    Iy_ss: 0.185
    wy_ss: 1.1913 
    whashy_ss: 1.1969 
    h1y_ss: 1.6711
    h2y_ss: 2.8441
    Ny_ss: 0.4394
    Khaty_ss: 7.4724
    Ky_ss: 7.4724
    mcy_ss: 0.727 
    x1y_ss: 5.347
    x2y_ss: 6.60
    Yy_ss: 0.748
    nupy_ss: 1.0006
