constants:
    gamma_N: 0.299
    iN: 0.0
    iT: 0.0
    kappa: 1.5
    #calibrated
    A_prod: 1.179
    omega: 1.75
    yT_bar: 1.0
    rf_star: 0.0159
    alpha: 0.8
    sigma: 2.0
    beta: 0.98
    theta: 11.0
    eta: 0.76
    calvo: 0.733
    pi_targ: 0.0074
    phi_pi: 2.0
    pTstar: 1.0
    p_xbar: 1.0
    rho_rf: 0.0
    rho_yT: 0.537
    sigma_rf: 0.0
    sigma_delta: 0.0025
    std_yT: 0.0134
    #shocks
    sigma_rf: 0.0
    sigma_yT: 0.0134
    sigma_delta: 0.0025
    # ewma rhos
    rho_kappa_ewma: 0.999
    rho_debt_to_gdp_ewma: 0.999
    rho_budget_viol_ewma: 0.999
    target_debt_to_gdp: 1.4
    target_budget_viol: 0.04
    nu_eps: 1e-4