states:
  #exogenous state variables
  - name: Ax
  - name: Gx
  - name: Zx
  - name: nux
  - name: psix
  - name: mx 
  #endogenous state variables
  - name: Kx
    init:
      distribution: uniform
      kwargs:
        minval: 6.7
        maxval: 8.2 
  - name: Cx
    init:
      distribution: uniform
      kwargs:
        minval: 0.37
        maxval: 0.45  
  - name: Ix
    init:
      distribution: uniform
      kwargs:
        minval: 0.13
        maxval: 0.24    
  - name: Yx
    init:
      distribution: uniform
      kwargs:
        minval: 0.67
        maxval: 0.82   
  - name: wx
    init:
      distribution: uniform
      kwargs:
        minval: 1.07
        maxval: 1.31    
  - name: nupx
    init:
      distribution: uniform
      kwargs:
        minval: 1.0
        maxval: 1.002   
  - name: pix
    init:
      distribution: uniform
      kwargs:
        minval: -0.01
        maxval: 0.02 
  - name: ix
    init:
      distribution: uniform
      kwargs:
        minval: -0.005
        maxval: 0.025     
policies:
  - name: lambday
    bounds: 
      lower: 0.1
      upper: 7.0
    activation: implied   
  - name: muy
    bounds: 
      lower: 0.1
      upper: 4.0
    activation: implied         
  - name: Cy
    bounds: 
      lower: 0.001
      upper: 0.12
    #activation: implied         
  - name: iy
    bounds: 
      lower: -0.06
      upper: 0.1
    activation: implied         
  - name: piy
    bounds: 
      lower: -0.15
      upper: 0.15
    activation: implied         
  - name: pihashy
    bounds: 
      lower: -0.5
      upper: 1.5
    activation: implied         
  - name: Ry
    bounds: 
      lower: -0.02
      upper: 0.15   
    activation: implied         
  - name: uy
    bounds: 
      lower: 0.1
      upper: 1.6
    activation: implied         
  - name: Iy
    bounds: 
      lower: 0.01
      upper: 10.0
    activation: implied         
  - name: wy
    bounds: 
      lower: 0.01
      upper: 1.5
    activation: implied         
  - name: whashy
    bounds: 
      lower: 0.01
      upper: 1.5
    activation: implied         
  - name: h1y
    bounds: 
      lower: 0.01
      upper: 20.0
    activation: implied         
  - name: h2y
    bounds: 
      lower: 0.01
      upper: 20.0
    activation: implied         
  - name: Ny
    bounds: 
      lower: 0.2
      upper: 0.8 
    activation: implied         
  - name: Khaty
    bounds: 
      lower: 0.01
      upper: 12.0  
    activation: implied         
  - name: Ky
    bounds: 
      lower: 4.0
      upper: 10.0    
    activation: implied         
  - name: mcy
    bounds: 
      lower: 0.01
      upper: 2.5    
    activation: implied         
  - name: x1y
    bounds: 
      lower: 2.0
      upper: 100.0  
    activation: implied         
  - name: x2y
    bounds: 
      lower: 3.0
      upper: 20.0  
    activation: implied         
  - name: Yy
    bounds: 
      lower: 0.4
      upper: 1.1  
    activation: implied         
  - name: nupy
    bounds: 
      lower: 0.7
      upper: 1.3  
    activation: implied         
definitions:
  - name: delta_1
