layers:
  - hidden:
     units: 5
     type: dense
     activation: relu
  - hidden:
     units: 5
     type: dense
     activation: relu
  - hidden:
     units: 5
     type: dense
     activation: relu
  - hidden:
     units: 5
     type: dense
     activation: relu
  - output:
     type: dense
     activation: linear