layers:
  - hidden:
     units: 10
     type: dense
     activation: swish
     init_scale: 0.1   
  - output:
     type: dense
     activation: linear
     init_scale: 0.1
net_initializer_mode: fan_in
net_initializer_distribution: truncated_normal