hydra: 
  run:
    dir: runs/${MODEL_NAME}/${now:%Y-%m-%d}/${now:%H-%M-%S}
defaults:
#  - constants: nkdsge_start
  - constants: nkdsge_no_util_norm
  - net: large
  - optimizer: baseline
  - run: large
#  - variables: nkdsge_ss 
  - variables: nkdsge_no_util_norm
seed: 666
# can be NEW, LATEST, or a given checkpoint filename
STARTING_POINT: NEW
CHECKPOINT_INTERVAL: 10
MAX_TO_KEEP_NUMBER: 10
MODEL_NAME: nkdsge_no_util_norm
#False-> Simulation; True -> draw 
initialize_each_episode: False
error_filename: error_file.txt
enable_check_numerics: False

